name: widget_examples_tester
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/widget_examples_tester/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  dropdown_search:
  flutter_riverpod:
  theme_builder:
    git:
      url: https://github.com/tmcmaster/theme_builder.git
  widget_tester:
    git:
      url: https://github.com/tmcmaster/widget_tester.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  faker:
